controller_joint_names:
- ''
- left_hand_thumb_rota_block_joint
- left_hand_thumb_rotaback_joint2
- left_hand_thumb_MCP_joint
- left_hand_thumb_PIP_joint
- left_hand_index_MCP_joint
- left_hand_index_swing_joint
- left_hand_index_PIP_joint
- left_hand_index_DIP_joint
- left_hand_mid_MCP_joint
- left_hand_mid_swing_joint
- left_hand_mid_PIP_joint
- left_hand_mid_DIP_joint
- left_hand_ring_MCP_joint
- left_hand_ring_swing_joint
- left_hand_ring_PIP_joint
- left_hand_ring_DIP_joint
- left_hand_pinky_MCP_joint
- left_hand_pinky_swing_joint
- left_hand_pinky_PIP_joint
- left_hand_pinky_DIP_joint
